import type { NextPage } from "next";
import Head from "next/head";
import ProtectedRoute from "../../../src/templates/ProtectedRoute";
import Watch from "../../../src/templates/Watch";

const WatchPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Assistir - WVW</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ProtectedRoute>
        <Watch />
      </ProtectedRoute>
    </>
  );
};

export default WatchPage;
