import type { NextPage } from "next";
import Head from "next/head";
import AppLayout from "../../src/layouts/AppLayout";
import Search from "../../src/templates/Search";

const Welcome: NextPage = () => {
  return (
    <>
      <Head>
        <title>WVW</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>{/* <Search /> */}</AppLayout>
    </>
  );
};

export default Welcome;
